CREATE DATABASE IF NOT EXISTS carematching;
USE carematching;

CREATE TABLE IF NOT EXISTS pending_payment (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID VARCHAR(100) NOT NULL,
  PAYMENT_KEY VARCHAR(255) NOT NULL,
  PRICE INT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONFIRMED BOOLEAN NOT NULL DEFAULT FALSE,
  FAIL_REASON VARCHAR(255)
);

INSERT INTO pending_payment (ORDER_ID, PAYMENT_KEY, PRICE, CREATED_AT, CONFIRMED, FAIL_REASON) VALUES
('ORDER-1001', 'ok', 10000, NOW() - INTERVAL 1 MINUTE, FALSE, NULL),
('ORDER-1002', 'badkey', 20000, NOW() - INTERVAL 2 MINUTE, FALSE, NULL),
('ORDER-1003', 'ok', 15000, NOW() - INTERVAL 3 MINUTE, FALSE, NULL),
('ORDER-1004', 'expired', 5000, NOW() - INTERVAL 20 MINUTE, FALSE, NULL);
